services:
    web:
        build: .
        container_name: web
        ports:
        - "8080:8080"
        - "8088:8088"
        environment:
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
