services:
    web:
        build: .
        ports:
        - "8080:8080"
        - "8088:8088"
        environment:
            - PLACEHOLDER=PLACEHOLDER
        secrets:
            - secret_placeholder
