openapi: 3.0.3
info:
    title: Forwarder API
    description: The forwarder api forwards warnings to the appropriate channel
    version: 0.0.1
servers:
    - url: http://localhost:80/forward
      description: The forwarder server
paths:
    /forward:
        post:
            tags:
                - ForwarderService
            summary: forward ForwarderService
            description: Forwards a warning to the appropriate channel
            operationId: ForwarderService#forward
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Message'
                        example:
                            description: Perspiciatis et.
                            name: Exercitationem cumque eius minus perferendis.
                            type: Qui ut laborum aut.
            responses:
                "201":
                    description: Created response.
components:
    schemas:
        Message:
            type: object
            properties:
                description:
                    type: string
                    description: The description of the event
                    example: Ab dolorem vel omnis ipsum facilis.
                name:
                    type: string
                    description: The name of the event
                    example: Est quo.
                type:
                    type: string
                    description: The type of message
                    example: Ut exercitationem et qui odit.
            example:
                description: Occaecati necessitatibus.
                name: Optio iusto hic.
                type: Exercitationem in tenetur quasi.
            required:
                - type
                - name
                - description
tags:
    - name: ForwarderService
      description: The forwarder service forwards warnings to the appropriate channel
